UBUNTU: SAUCE: rfi-flush: Fix rename of pseries_setup_rfi_flush()
CVE-2017-5754 (Meltdown)
BugLink: https://bugs.launchpad.net/bugs/1742772

This was missed in commit e23274b255cb ("rfi-flush: Call
setup_rfi_flush() after LPM migration"), leading to:

  arch/powerpc/platforms/pseries/setup.c:519: undefined reference to `.pseries_setup_rfi_flush'

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>