UBUNTU: SAUCE: rfi-flush: Fix kernel package build using bootmem
CVE-2017-5754 (Meltdown)
BugLink: https://bugs.launchpad.net/bugs/1742772

This introduces functional changes, see comment in file.

Build error:

    arch/powerpc/kernel/setup_64.c: In function 'init_fallback_flush':
    arch/powerpc/kernel/setup_64.c:823:6: error: the address of 'l1d_flush_fallback_area' will always evaluate as 'true' [-Werror=address]
      if (l1d_flush_fallback_area)
          ^
    cc1: all warnings being treated as errors
    make[1]: *** [arch/powerpc/kernel/setup_64.o] Error 1

Signed-off-by: Mauricio Faria de Oliveira <mauricfo@linux.vnet.ibm.com>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>