UBUNTU: SAUCE: Move __this_cpu_{read,write} to percpu-ubuntu.h
To fix compilation errors of the following sort which happen when
asm/hardirq.h is included from an arch header (like in the subsequent
commit ("x86/irq: Let interrupt handlers set kvm_cpu_l1tf_flush_l1d"):

./arch/x86/include/asm/smp.h:138:20: error: static declaration of 'smp_send_reschedule' follows non-static declaration
 static inline void smp_send_reschedule(int cpu)
                    ^
In file included from include/linux/percpu.h:5:0,
                 from ./arch/x86/include/asm/hardirq.h:5,
                 from ./arch/x86/include/asm/apic.h:15,
                 from ./arch/x86/include/asm/smp.h:13,
                 from ./arch/x86/include/asm/mmzone_64.h:10,
                 from ./arch/x86/include/asm/mmzone.h:4,
                 from include/linux/mmzone.h:922,
                 from include/linux/gfp.h:4,
                 from include/linux/slab.h:14,
                 from include/linux/crypto.h:24,
                 from arch/x86/kernel/asm-offsets.c:8:
include/linux/smp.h:77:13: note: previous declaration of 'smp_send_reschedule' was here
 extern void smp_send_reschedule(int cpu);
             ^
make[1]: *** [arch/x86/kernel/asm-offsets.s] Error 1

linux/percpu.h is a high-level include file that shouldn't be included from
arch headers but it's needed in asm/hardirq.h for __this_cpu_{read,write}.\
Eventually the headers linux/smp.h and arch/smp.h are pulled in as well but
in the wrong order, which leads to the above error.

Fix this for now by moving the definitions required by hardirq.h into a
separate file and include only that. Note that the later commit
a32f8d8eda8b ("percpu: move {raw|this}_cpu_*() definitions to
include/linux/percpu-defs.h") from v3.17 moves all these defines into
percpu-defs.h to get rid of the very same issue.

CVE-2018-3620
CVE-2018-3646

Signed-off-by: Juerg Haefliger <juergh@canonical.com>